### PR TITLE
windows: fix "file does not exist" (fix #100 #115)

### LINKED ISSUE #100: Not able to get devices on windows
Ipconfig o/p  on windows 
Unknown adapter wg0:
   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 10.113.0.0
   Subnet Mask . . . . . . . . . . . : 255.255.255.255
   Default Gateway . . . . . . . . . :

wg o/p gives the below o/p 
interface: wg0
  public key: +71MjydauuTHO0CBi+2sNfuN+ZYffUT0Qc6NOzl5ij0=
  private key: (hidden)
  listening port: 58816

wgClient.ConfigureDevice() return with error "file does not exist"

In one of the windows box I could verify it works and gets the device only after couple of failed attempts. But it fails consistently on few others. Any reason for this to happen. Plz advice.

### PR DESCRIPTION
**Pull request by Adphi**
This pull request provides a fix to the `file not found` error on windows.

https://github.com/golang/sys/blob/97ca703d548df069cb02aacea9efc3093ffdc3c4/windows/setupapi_windows.go#L1417-L1425

### CODE REVIEW

**Comment by zx2c4** [comment]
Thanks. From x/sys/windows:

```go
func CM_Get_DevNode_Status(status *uint32, problemNumber *uint32, devInst DEVINST, flags uint32) error {
        ret := cm_Get_DevNode_Status(status, problemNumber, devInst, flags)
        if ret == CR_SUCCESS {
                return nil
        }
        return ret
}
```

**Review by zx2c4 — APPROVED** [review]
Might want to fix the commit message, but other than that, this is the correct fix.

**Comment by Adphi** [comment]
> Might want to fix the commit message, but other than that, this is the correct fix.

You do you want as commit message ?

**Comment by zx2c4** [comment]
```
internal/windows: check for nil error rather than CR_SUCCESS

This prevents failing with a "file not found" error.

Fixes #100.
Fixes #115.

Signed-off-by: Your Name <your@email>
```

**Comment by Adphi** [comment]
Done 😉

**Comment by mdlayher** [comment]
Don't worry about CI, planning to fix that up in the next few days hopefully. LGTM.

**Pull request merged**
