### PR TITLE
internal/freebsd: add initial version of FreeBSD support

### LINKED ISSUE #91: internal/wgfreebsd: support for new FreeBSD kernel interface
@mattmacy is working on a FreeBSD kernel implementation of WireGuard at https://github.com/mattmacy/wg-fbsd and the repo is going to be moved to https://git.zx2c4.com/wireguard-freebsd/about/ soon. We should support this interface.

### PR DESCRIPTION
**Pull request by stv0g**
Signed-off-by: Steffen Vogel <post@steffenvogel.de>

Closes #91

### CODE REVIEW

**Comment by stv0g** [comment]
The second commit just slipped into this PR to make the CI pass

**Comment by mdlayher** [comment]
Thanks for your work on this. I will try to spin up a VM to test amd64 in the next couple of days.

Would it be possible to set up a FreeBSD case in https://github.com/WireGuard/wgctrl-go/blob/master/.cibuild.sh to configure a kernel device for use in CI?

**Comment by stv0g** [comment]
> Would it be possible to set up a FreeBSD case in https://github.com/WireGuard/wgctrl-go/blob/master/.cibuild.sh to configure a kernel device for use in CI?

Yes, thats done in my latest commit. We are currently missing only some Go unit tests as I couldnt take those from the OpenBSD client.

**Comment by stv0g** [comment]
Oh no, the CI fails with:

```bash
ifconfig: SIOCIFCREATE2: Invalid argument
```

However, the same command succeeds on my VM.
I dont know, maybe its due to a BSD jail? Or a kernel without WireGuard support compiled in?

**Comment by stv0g** [comment]
@mdlayher Please ignore my previous comment. I jsut forgot to install the wireguard-kmod package from the FreeBSD ports.

Now most of the tests pass. I just got stuck with the following, which I believe is a bug in the FreeBSD kernel implementation:

```
=== RUN   TestIntegrationClient/configure_many_IPs/wg0
    client_integration_test.go:268: unexpected number of configured peer IPs (-want +got):
          int(
        - 	1022,
        + 	511,
          )
```

**Comment by stv0g** [comment]
Okay, all issues fixed. Test succeed in the CI and on my VM.

Currently, the FreeBSD kernel implementation does not support the PeerConfig UpdateOnly flag.
I am now throwing an error if a user attempts to use it.
I think this is a cleaner solution than trying to emulate it in userspace as this can be racy.
We should wait for the kernel module to add this missing feature.

@mdlayher Feel free to merge it once you are happy. I am considering the PR complete.

**Comment by mdlayher** [comment]
Sorry for the delay, I have been focused on work but haven't forgotten about this! I am spinning up a VM this morning to give it a test run and will merge if all seems good. Thank you for your contribution.

**Comment by mdlayher** [comment]
I downloaded a FreeBSD 14.0-CURRENT image and spun it up in a VM. Looks like at least some of the integration tests do work, but it's hanging up trying to configure many peers on my setup. I remember this test being problematic for Linux a while back but don't know anything about the FreeBSD implementation:

```
[matt@freebsd ~/src/wgctrl-go]$ sudo WGCTRL_INTEGRATION=yesreallydoit ./wgctrl.test -test.v
=== RUN   TestClientClose
--- PASS: TestClientClose (0.00s)
=== RUN   TestClientDevices
--- PASS: TestClientDevices (0.00s)
=== RUN   TestClientDevice
=== RUN   TestClientDevice/first_error
=== RUN   TestClientDevice/not_found
=== RUN   TestClientDevice/first_not_found
=== RUN   TestClientDevice/first_ok
--- PASS: TestClientDevice (0.00s)
    --- PASS: TestClientDevice/first_error (0.00s)
    --- PASS: TestClientDevice/not_found (0.00s)
    --- PASS: TestClientDevice/first_not_found (0.00s)
    --- PASS: TestClientDevice/first_ok (0.00s)
=== RUN   TestClientConfigureDevice
=== RUN   TestClientConfigureDevice/first_error
=== RUN   TestClientConfigureDevice/not_found
=== RUN   TestClientConfigureDevice/first_not_found
=== RUN   TestClientConfigureDevice/first_ok
--- PASS: TestClientConfigureDevice (0.00s)
    --- PASS: TestClientConfigureDevice/first_error (0.00s)
    --- PASS: TestClientConfigureDevice/not_found (0.00s)
    --- PASS: TestClientConfigureDevice/first_not_found (0.00s)
    --- PASS: TestClientConfigureDevice/first_ok (0.00s)
=== RUN   TestIntegrationClient
=== RUN   TestIntegrationClient/get
=== RUN   TestIntegrationClient/get/wg0
    client_integration_test.go:132: device: wg0: L+V9o0fNYkMVKNqsX7spBzD/9oSvxM/C7ZCZX1jLO3Q=
=== RUN   TestIntegrationClient/configure
=== RUN   TestIntegrationClient/configure/wg0
    client_integration_test.go:156: before: wg0: L+V9o0fNYkMVKNqsX7spBzD/9oSvxM/C7ZCZX1jLO3Q=
    client_integration_test.go:211:  after: wg0: hK/YxCsl36tupBwc41tSrY4atU8sYC6ecF2YCEiAhio=
        - peer: uyMA2Jgl+f3KDWM98+Ix6nnQ4iEzVUEfMg9hD/X64l8=, IPs: 192.0.2.0/32, 2001:db8::/128
        
=== RUN   TestIntegrationClient/configure_many_IPs
=== RUN   TestIntegrationClient/configure_many_IPs/wg0
    client_integration_test.go:271: device: wg0: 1022 IPs
=== RUN   TestIntegrationClient/configure_many_peers
=== RUN   TestIntegrationClient/configure_many_peers/wg0

```

**Comment by mdlayher** [comment]
Either way this seems like a good starting point and I think we can iterate from here. Thank you!

**Pull request closed without merging**
